web/market/posts/routes.py
from flask import render_template, flash, url_for, redirect, request, abort, Blueprint
from flask_login.utils import login_required
from flask_login import current_user
from market import db
from market.models import Post
from market.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/<int:post_id>')
@login_required
def post_page(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.forum_page'))
    return render_template('create_update_post.html', form=form, legend='New Post')


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # Forbidden route
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('You post has been updated!', category='success')
        return redirect(url_for('posts.post_page', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_update_post.html', title='Update Post', form=form,
                           legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # Forbidden route
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Your post has been deleted!', category='success')
    return redirect(url_for('main.forum_page'))

web/market/templates/includes/items_modals.html
<style>
  .modal-content {
    background-color: #212121;
  }
</style>

<!-- More Info -->
<div class="modal fade" id="Modal-MoreInfo-{{ item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ item.name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      {{ item.description }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Purchase Confirm -->
<div class="modal fade" id="Modal-PurchaseConfirm-{{ item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ item.name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
        {{ purchase_form.hidden_tag() }}
        <h5 class="text-center">Are you sure you want to buy <br> {{ item.name }} for {{ item.price }}$ ?</h5>
        <br>
        <p class="text-center">By clicking purchase, you purchase this item.</p>
        <div class="d-grid gap-2">
          <input id="purchased_item" name="purchased_item" type="hidden" value="{{ item.name }}">
          {{ purchase_form.submit(class="btn btn-success") }}
        </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/market/templates/includes/owned_items_modals.html
<style>
  .modal-content {
    background-color: #212121;
  }
</style>

<!-- Selling Confirm -->
<div class="modal fade" id="Modal-SellingConfirm-{{ owned_item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ owned_item.name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="background-color:white"></button>
      </div>
      <div class="modal-body">
        <form method="POST">
        {{ selling_form.hidden_tag() }}
        <h5 class="text-center">Are you sure you want to sell <br> {{ owned_item.name }} for {{ owned_item.price }}$ ?</h5>
        <br>
        <p class="text-center">By clicking sell, you will put this item back on market</p>
        <div class="d-grid gap-2">
          <input id="sold_item" name="sold_item" type="hidden" value="{{ owned_item.name }}">
          {{ selling_form.submit(class="btn btn-danger") }}
        </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

web/market/templates/includes/post_modals.html
<style>
  .modal-content {
    background-color: #212121;
  }
</style>

<!-- Delete Post -->
<div class="modal fade" id="Modal-DeletePost" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Post?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>