web/market/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

web/market/main/routes.py
from flask import render_template, request, flash, redirect, url_for, Blueprint
from flask_login.utils import login_required, current_user
from market.models import Item, Post
from market.users.forms import PurchaseItemForm, SellItemForm

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home_page():
    return render_template('home.html')


@main.route('/market', methods=['GET', 'POST'])
@login_required
def market_page():
    purchase_form = PurchaseItemForm()
    selling_form = SellItemForm()
    if request.method == 'POST':
        # Purchase Item Logic
        purchased_item = request.form.get('purchased_item')
        p_item_object = Item.query.filter_by(name=purchased_item).first()
        if p_item_object:
            if current_user.can_purchase(p_item_object):
                p_item_object.buy(current_user)
                flash(
                    f'Congratulations! You have just purchased {p_item_object.name} for {p_item_object.price}$', category='success')
            else:
                flash(
                    f"Unfortunately, you don't have enough money to purchase {p_item_object.name}", category='danger')
        # Sell Item Logic
        sold_item = request.form.get('sold_item')
        s_item_object = Item.query.filter_by(name=sold_item).first()
        if s_item_object:
            if current_user.can_sell(s_item_object):
                s_item_object.sell(current_user)
                flash(
                    f'Congratulations! You have just sold {s_item_object.name} for {s_item_object.price}$', category='success')
            else:
                flash(
                    f"Something went wrong with selling {s_item_object.name}", category='danger')
        return redirect(url_for('main.market_page'))

    if request.method == 'GET':
        items = Item.query.filter_by(owner=None)
        owned_items = Item.query.filter_by(owner=current_user.id)
        return render_template('market.html', items=items, purchase_form=purchase_form, owned_items=owned_items, selling_form=selling_form)


@main.route('/forum')
@login_required
def forum_page():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.time_created.desc()).paginate(page=page, per_page=4)
    return render_template('forum.html', posts=posts)

web/market/posts/routes.py
from flask import render_template, flash, url_for, redirect, request, abort, Blueprint
from flask_login.utils import login_required
from flask_login import current_user
from market import db
from market.models import Post
from market.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/<int:post_id>')
@login_required
def post_page(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.forum_page'))
    return render_template('create_update_post.html', form=form, legend='New Post')


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # Forbidden route
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('You post has been updated!', category='success')
        return redirect(url_for('posts.post_page', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_update_post.html', title='Update Post', form=form,
                           legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # Forbidden route
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Your post has been deleted!', category='success')
    return redirect(url_for('main.forum_page'))

web/market/users/routes.py
from flask import flash, redirect, url_for, render_template, request, Blueprint
from flask_login import login_user, logout_user, login_required, current_user
from market import db
from market.users.forms import RegisterForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from market.models import User, Post
from market.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():
        user_to_create = User(username=form.username.data,
                              email_address=form.email_address.data,
                              password=form.password1.data)
        db.session.add(user_to_create)
        db.session.commit()
        login_user(user_to_create)
        flash(
            f'Account has been created successfully! You are now logged in as {user_to_create.username}', category='success')
        return redirect(url_for('main.market_page'))
    # If there are no errors from validations
    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(
                f'There was an error with creating a user: {err_msg}', category='danger')
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():
        attempted_user = User.query.filter_by(
            username=form.username.data).first()
        if attempted_user and attempted_user.check_password_correction(
            attempted_password=form.password.data
        ):
            login_user(attempted_user)
            flash(
                f'Success! You are logged in as {attempted_user.username}', category='success')
            return redirect(url_for('main.market_page'))
        else:
            flash('Username and password are not match. Please try again',
                  category='danger')
    return render_template('login.html', form=form)


@users.route('/logout')
def logout_page():
    logout_user()
    flash('You have been logged out', category='info')
    return redirect(url_for('main.home_page'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account_page():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email_address = form.email_address.data
        db.session.commit()
        flash(f'Your account has been updated!', category='success')
        return redirect(url_for('users.account_page'))
    if form.picture.errors:
        for err_msg in form.picture.errors:
            flash(err_msg, category='danger')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email_address.data = current_user.email_address
    image_file = url_for(
        'static', filename=f'profile_pics/{current_user.image_file}')
    return render_template('account.html', image_file=image_file, form=form)


@users.route('/forum/<string:username>')
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.time_created.desc())\
        .paginate(page=page, per_page=4)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return(url_for('main.home_page'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(
            email_address=form.email_address.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', category='info')
        return redirect(url_for('users.login_page'))
    if form.email_address.errors:
        for err_msg in form.email_address.errors:
            flash(err_msg, category='danger')
    return render_template('reset_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return(url_for('main.home_page'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token', category='warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = form.password1.data
        db.session.commit()
        flash(f'You password has been updated! You are now able to log in.',
              category='success')
        return redirect(url_for('users.login_page'))
    if form.errors != {}:
        flash(f'Passwords do not match.', category='danger')
    return render_template('reset_token.html', form=form)

web/market/templates/account.html
{% extends 'base.html' %} {% block title %} Your Profile {% endblock %} {% block
content %}
<div class="container text-center w-25">
  <div class="media m-3">
    <img
      src="{{ image_file }}"
      alt="Profile Picture"
      class="img-thumbnail"
      style="height: 120px; width: 125px"
    />
    <div class="media-body">
      <h5 class="mt-3">{{ current_user.username}}</h5>
      <p>{{ current_user.email_address }}</p>
    </div>
  </div>
  <br />
  <form method="POST" class="form-register" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <h1 class="h3 mb-3 font-weight-normal">Update Your Account</h1>
    {{ form.username.label() }} {{ form.username(class="form-control",
    placeholder="Username") }} {{ form.email_address.label() }} {{
    form.email_address(class="form-control", placeholder="Email Address") }}
    <br />
    {{ form.picture.label() }} {{ form.picture(class="form-control",
    type="file") }}
    <br />
    <div class="d-grid gap-2">
      {{ form.submit(class="btn btn-lg btn-primary") }}
    </div>
  </form>
</div>
{% endblock %}

web/market/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.home_page') }}">
          Phone Market
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-phone" viewBox="0 0 16 16">
            <path d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h6zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z"/>
            <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
          </svg>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('main.home_page') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('main.market_page') }}">Market</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('main.forum_page') }}">Forum</a>
            </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link fw-bold" style="color:lawngreen">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-coin" viewBox="0 0 16 16">
                  <path d="M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9H5.5zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518l.087.02z"/>
                  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                  <path fill-rule="evenodd" d="M8 13.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zm0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/>
                </svg>
                {{ current_user.prettier_budget }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.account_page') }}">
                Logged as <strong>{{ current_user.username }}</strong>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.account_page') }}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.logout_page') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" aria-current="login" href="{{ url_for('users.login_page') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="register" href="{{ url_for('users.register_page') }}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <br>
    {% block content %}
    {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous"
    ></script>
  </body>
  <style>
    body {
      background-color: #212121;
      color: white;
    }
  </style>
</html>

web/market/templates/create_update_post.html
{% extends 'base.html' %}
{% block title %}
  New Post
{% endblock %}

{% block content %}
<body>
  <div class="container text-center w-50">
    <form method="POST" class="form-signin">
      {{ form.hidden_tag() }}
      <h1 class="h3 mb-3 font-weight-normal">
        {{ legend }}
      </h1>
      <div class="mb-3 mx-5 px-5">
        {{ form.title.label() }}
        {{ form.title(class="form-control", autocomplete="off") }}
      </div>
      <div class="mb-3">
        {{ form.content.label() }}
        {{ form.content(class="form-control", rows="10") }}
      </div>
      <div class="d-grid gap-2">
        {{ form.submit(class="btn btn-lg btn-primary") }}
      </div>
    </form>
  </div>
</body>
{% endblock %}

web/market/templates/forum.html
{% extends 'base.html' %} 
{% block title %}
  Forum
{% endblock %} 

{% block content %}
<div class="container w-50">
  <div class="jumbotron text-center">
    <h1 class="display-4">Forum</h1>
    <p class="lead">Let's talk about technology!</p>
    <hr class="my-4">
    <p class="lead">
    </p>
  </div>
  {% for post in posts.items %}
  <div class="media m-4 p-3 border rounded">
    <div class="media-body m-2">
      <a class="link-info text-decoration-none" href="{{ url_for('users.user_posts', username=post.author.username) }}">
        <img class="mx-4 rounded-circle float-start",
        src="{{ url_for('static', filename='/profile_pics/' + post.author.image_file) }}",
        alt="Generic placeholder image",
        style="width:64px;height:64px">
        {{ post.author.username }}
      </a>
       <br>
       <small>{{ post.time_created.strftime("%Y-%m-%d %H:%M") }}</small>
       <hr class="mt-4">
      <h3 class="mt-0"><a class="link-light text-decoration-none" href="{{ url_for('posts.post_page', post_id=post.id) }}">{{ post.title }} </a></h3>
      {{ post.content }}
    </div>
   </div>
   {% endfor %}
   <div class="text-center">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a href="{{ url_for('main.forum_page', page=page_num) }}" class="btn btn-info mb-4">{{ page_num }}</a>
      {% else %}
      <a href="{{ url_for('main.forum_page', page=page_num) }}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
      {% endif %}
  {% else %}
   ...
  {% endif %}
  {% endfor %}
</div>
</div>
{% endblock %}

web/market/templates/home.html
{% extends 'base.html' %} {% block title %} Home Page {% endblock %} {% block
content %}
<div class="container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome!</h1>
    <p class="lead">to our online market</p>
    <hr class="my-4" />
    <p class="m-1">Here you are given 1000$ for <strong>FREE</strong></p>
    <p class="m-1">So that you can buy smartphones</p>
    <p>You can also enjoy your time on our forum</p>
    <p class="lead">
      <a
        class="btn btn-primary btn-lg"
        href="{{ url_for('main.market_page') }}"
        role="button"
        >Get Started</a
      >
    </p>
    <img
      src="{{ url_for('static', filename='marketplace.jpg') }}"
      class="img-thumbnail m-3"
      alt="Marketplace"
      width="350px"
    />
  </div>
</div>
{% endblock %}

web/market/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login Page
{% endblock %}

{% block content %}
<body>
  <div class="container text-center w-25">
    <form method="POST" class="form-signin">
      {{ form.hidden_tag() }}
      <br>
      <h1 class="h3 mb-3 font-weight-normal">
        Please Log In
      </h1>
      {{ form.username.label() }}
      {{ form.username(class="form-control", placeholder="Username") }}

      {{ form.password.label() }}
      {{ form.password(class="form-control", placeholder="Password") }}
      <br>
      <div class="checkbox mb-3">
        <a href="{{ url_for('users.register_page') }}" class="link-light">Do not have an account?</a>
      </div>
      <div class="checkbox mb-3">
        <h6></h6>
        <a href="{{ url_for('users.reset_request') }}" class="link-light">Forgot password?</a>
      </div>
      <div class="d-grid gap-2">
        {{ form.submit(class="btn btn-lg btn-primary") }}
      </div>
    </form>
  </div>
</body>
{% endblock %}

web/market/templates/market.html
{% extends 'base.html' %} 
{% block title %}
Phone Market
{% endblock %} 
{% block content %}
<div class="row m-3">
   <div class="col-8">
      <h2>Available Items</h2>
      <p>Click on one of the items to start buying.</p>
      <br>
      <table class="table table-hover table-dark">
         <thead>
            <tr>
               <th scope="col">ID</th>
               <th scope="col">Name</th>
               <th scope="col">Barcode</th>
               <th scope="col">Price</th>
               <th scope="col">Options</th>
            </tr>
         </thead>
         <tbody>
            <!-- Your rows inside the table HERE: -->
            {% for item in items %}
            {% include 'includes/items_modals.html' %}
            <tr>
               <td>{{ item.id }}</td>
               <td>{{ item.name }}</td>
               <td>{{ item.barcode }}</td>
               <td>{{ item.price }}$</td>
               <td>
                  <button class="btn btn-outline btn-info" data-bs-toggle="modal" data-bs-target="#Modal-MoreInfo-{{ item.id }}">More Info</button>
                  <button class="btn btn-outline btn-success" data-bs-toggle="modal" data-bs-target="#Modal-PurchaseConfirm-{{ item.id }}">
                  Purchase this item
                  </button>
               </td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
   </div>
   <div class="col-4">
    <h2>Owned Items</h2>
    <p>Click on sell item to put item back on the market.</p>
    <br>
    <div class="row">
      {% for owned_item in owned_items %}
      {% include 'includes/owned_items_modals.html' %}
        <div class="card w-50 bg-dark">
          <div class="card-body">
            <h5 class="card-title">{{ owned_item.name }}</h5>
            <p class="card-text">This item costs {{ owned_item.price }}$</p>
            <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#Modal-SellingConfirm-{{ owned_item.id }}">Sell</a>
          </div>
        </div>
      {% endfor %}
    </div>
   </div>
</div>
{% endblock %}

web/market/templates/post.html
{% extends 'base.html' %} 
{% block title %}
  {{ title }}
{% endblock %} 

{% block content %}
<div class="container w-50">
  <div class="media m-4 p-3 border rounded">
    <img class="mx-4 rounded-circle float-start",
    src="{{ url_for('static', filename='/profile_pics/' + post.author.image_file) }}",
    alt="Generic placeholder image",
    style="width:64px;height:64px">
    
    <div class="media-body m-2">
      <a class="link-info text-decoration-none" href="{{ url_for('users.user_posts', username=post.author.username) }}">
        {{ post.author.username }}
      </a>
       <br>
      <small>{{ post.time_created.strftime("%Y-%m-%d %H:%M") }}</small>
      {% if current_user == post.author %}
        {% include 'includes/post_modals.html' %}
        <button type="button" class="btn btn-danger float-end mx-1" data-bs-toggle="modal" data-bs-target="#Modal-DeletePost">
          Delete
        </button>
        <a type="button" href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-primary float-end">Update</a>
      {% endif %}
      <hr class="mt-4">
      <h4 class="mt-0">{{ post.title }}</></h4>
      {{ post.content }}
    </div>
  </div>
</div>
{% endblock %}

web/market/templates/register.html
{% extends 'base.html' %} {% block title %} Register Page {% endblock %} {%
block content %}
<body>
  <div class="container text-center w-25">
    <form method="POST" class="form-register">
      {{ form.hidden_tag() }}
      <br />
      <h1 class="h3 mb-3 font-weight-normal">Create Your Account</h1>

      {{ form.username.label() }} {{ form.username(class="form-control mb-2",
      placeholder="Username") }} {{ form.email_address.label() }} {{
      form.email_address(class="form-control mb-2", placeholder="Email Address")
      }} {{ form.password1.label() }} {{ form.password1(class="form-control
      mb-2", placeholder="Password") }} {{ form.password2.label() }} {{
      form.password2(class="form-control mb-2", placeholder="Confirm Password")
      }}

      <div class="checkbox mb-3">
        <h6>Already have an account?</h6>
        <a
          href="{{ url_for('users.login_page') }}"
          class="btn btn-sm btn-secondary"
          >Log In</a
        >
      </div>
      <div class="d-grid gap-2">
        {{ form.submit(class="btn btn-lg btn-primary") }}
      </div>
    </form>
  </div>
</body>
{% endblock %}

web/market/templates/reset_request.html
{% extends 'base.html' %}
{% block title %}
Login Page
{% endblock %}

{% block content %}
<body>
  <div class="container text-center w-25">
    <form method="POST" class="form-signin">
      {{ form.hidden_tag() }}
      <br>
      <h1 class="h3 mb-3 font-weight-normal">
        Reset Password
      </h1>
      {{ form.email_address.label() }}
      {{ form.email_address(class="form-control", placeholder="Email") }}
      <br>
      <div class="d-grid gap-2">
        {{ form.submit(class="btn btn-lg btn-primary") }}
      </div>
    </form>
  </div>
</body>
{% endblock %}

web/market/templates/reset_token.html
{% extends 'base.html' %}
{% block title %}
Login Page
{% endblock %}

{% block content %}
<body>
  <div class="container text-center w-25">
    <form method="POST" class="form-signin">
      {{ form.hidden_tag() }}
      <br>
      <h1 class="h3 mb-3 font-weight-normal">
        Reset Password
      </h1>
      {{ form.password1.label() }}
      {{ form.password1(class="form-control", placeholder="Password") }}
      
      {{ form.password2.label() }}
      {{ form.password2(class="form-control", placeholder="Confirm Password") }}
      <br>
      <div class="d-grid gap-2">
        {{ form.submit(class="btn btn-lg btn-primary") }}
      </div>
    </form>
  </div>
</body>
{% endblock %}

web/market/templates/user_posts.html
{% extends 'base.html' %} 
{% block title %}
  Posts by {{ user.username }}
{% endblock %} 

{% block content %}
<div class="container w-50">
  <br>
  <h1 class="text-center">Posts by {{ user.username }}</h1>
  <p class="text-center">Total posts: ({{ posts.total }})</p>
  <hr class="my-4">
  <br>
  {% for post in posts.items %}
  <div class="media m-4 p-3 border rounded">
    <div class="media-body m-2">
      <a class="link-info text-decoration-none" href="{{ url_for('users.user_posts', username=post.author.username) }}">
        <img class="mx-4 rounded-circle float-start",
        src="{{ url_for('static', filename='/profile_pics/' + post.author.image_file) }}",
        alt="Generic placeholder image",
        style="width:64px;height:64px">
        {{ post.author.username }}
      </a>
       <br>
       <small>{{ post.time_created.strftime("%Y-%m-%d %H:%M") }}</small>
       <hr class="mt-4">
      <h3 class="mt-0"><a class="text-light text-decoration-none" href="{{ url_for('posts.post_page', post_id=post.id) }}">{{ post.title }} </a></h3>
      {{ post.content }}
    </div>
   </div>
   {% endfor %}
   <div class="text-center">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="btn btn-info mb-4">{{ page_num }}</a>
    {% else %}
      <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
    {% endif %}
  {% else %}
   ...
  {% endif %}
  {% endfor %}
</div>
</div>
{% endblock %}